#!/bin/bash 
#SBATCH --mail-type=FAIL #Mail events (NONE, BEGIN, END, FAIL, ALL)
#SBATCH --mail-user=e130@uea.ac.uk #Where to send mail
#SBATCH -p compute-64-512 #Which partition to use
#SBATCH --mem=20G #Maximum memory required for job
#SBATCH -t 128:00:00
#SBATCH --job-name=GTDB_RT #Arbitrary name for job
#SBATCH -o logs/GTDB_ribotyper-%j.out #Standard output log
#SBATCH -e logs/GTDB_ribotyper-%j.out #Standard error log
#SBATCH --cpus-per-task=36
#SBATCH --ntasks=1

export OMP_NUM_THREADS=36
module add python/anaconda/2020.11/3.8
module add hmmer/3.3

source /gpfs/home/e130/ribovore/env_vars
set -o xtrace

#

ribotyper -f -n 36  $current/GTDB/GTDB_ssu_temp.fna $current/GTDB/working_files/GTDB_ribotyper_output
